=== api-evangelist/amazon-panorama/json-schema/openapi-describe-device-job-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-panorama/refs/heads/main/json-schema/openapi-describe-device-job-response-schema.json",
  "title": "DescribeDeviceJobResponse",
  "description": "DescribeDeviceJobResponse schema from Amazon Panorama",
  "type": "object",
  "properties": {
    "CreatedTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/UpdateCreatedTime"
        },
        {
          "description": "When the job was created."
        }
      ]
    },
    "DeviceArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DeviceArn"
        },
        {
          "description": "The device's ARN."
        }
      ]
    },
    "DeviceId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DeviceId"
        },
        {
          "description": "The device's ID."
        }
      ]
    },
    "DeviceName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DeviceName"
        },
        {
          "description": "The device's name."
        }
      ]
    },
    "DeviceType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DeviceType"
        },
        {
          "description": "The device's type."
        }
      ]
    },
    "ImageVersion": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ImageVersion"
        },
        {
          "description": "For an OTA job, the target version of the device software."
        }
      ]
    },
    "JobId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/JobId"
        },
        {
          "description": "The job's ID."
        }
      ]
    },
    "JobType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/JobType"
        },
        {
          "description": "The job's type."
        }
      ]
    },
    "Status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/UpdateProgress"
        },
        {
          "description": "The job's status."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-panorama/examples/openapi-describe-device-job-response-example.json
{
  "CreatedTime": "example-string",
  "DeviceArn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "DeviceId": "resource-abc123",
  "DeviceName": "my-resource",
  "DeviceType": "standard",
  "ImageVersion": "1.0.0",
  "JobId": "resource-abc123",
  "JobType": "standard",
  "Status": "active"
}
